UI/WebStore/Components/BreadCrumbsViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using WebStore.Interfaces.Services;
using WebStore.Services.Mapping;
using WebStore.ViewModels;

namespace WebStore.Components
{
    public class BreadCrumbsViewComponent : ViewComponent
    {
        private readonly IProductData _ProductData;

        public BreadCrumbsViewComponent(IProductData ProductData) => _ProductData = ProductData;

        public IViewComponentResult Invoke()
        {
            var model = new BreadCrumbsViewModel();

            if (int.TryParse(Request.Query["SectionId"], out var section_id))
            {
                model.Section = _ProductData.GetSectionById(section_id).FromDTO();
                if (model.Section?.ParentId != null)
                    model.Section.Parent = _ProductData.GetSectionById((int)model.Section.ParentId).FromDTO();
            }

            if (int.TryParse(Request.Query["BrandId"], out var brand_id))
                model.Brand = _ProductData.GetBrandById(brand_id).FromDTO();

            if (int.TryParse(ViewContext.RouteData.Values["id"]?.ToString(), out var product_id))
                model.Product = _ProductData.GetProductById(product_id)?.Name;

            return View(model);
        }
    }
}

UI/WebStore/Controllers/CatalogController.cs
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using WebStore.Domain;
using WebStore.Domain.ViewModels;
using WebStore.Interfaces.Services;
using WebStore.Services.Mapping;

namespace WebStore.Controllers
{
    public class CatalogController : Controller
    {
        private const string __CatalogPageSize = "CatalogPageSize";

        private readonly IProductData _ProductData;
        private readonly IConfiguration _Configuration;

        public CatalogController(IProductData ProductData, IConfiguration Configuration)
        {
            _ProductData = ProductData;
            _Configuration = Configuration;
        }

        public IActionResult Index(int? BrandId, int? SectionId, int Page = 1, int? PageSize = null)
        {
            var page_size = PageSize
                ?? (int.TryParse(_Configuration[__CatalogPageSize], out var value) ? value : null);

            var filter = new ProductFilter
            {
                BrandId = BrandId,
                SectionId = SectionId,
                Page = Page,
                PageSize = page_size
            };

            var (products, total_count) = _ProductData.GetProducts(filter);

            return View(new CatalogViewModel
            {
                SectionId = SectionId,
                BrandId = BrandId,
                Products = products
                   .OrderBy(p => p.Order)
                   .FromDTO()
                   .ToView(),
                PageViewModel = new PageViewModel
                {
                    Page = Page,
                    PageSize = page_size ?? 0,
                    TotalItems = total_count
                }
            });
        }

        public IActionResult Details(int id)
        {
            var product = _ProductData.GetProductById(id);
            if (product is null) return NotFound();

            return View(product.FromDTO().ToView());
        }

        #region WebAPI

        public IActionResult GetFeaturesItems(int? BrandId, int? SectionId, int Page = 1, int? PageSize = null) =>
            PartialView("Partial/_FeaturesItems", GetProducts(BrandId, SectionId, Page, PageSize));

        private IEnumerable<ProductViewModel> GetProducts(int? BrandId, int? SectionId, int Page, int? PageSize) =>
            _ProductData.GetProducts(new ProductFilter
            {
                SectionId = SectionId,
                BrandId = BrandId,
                Page = Page,
                PageSize = PageSize ?? (int.TryParse(_Configuration[__CatalogPageSize], out var size) ? size : null)
            })
               .Products.OrderBy(p => p.Order)
               .FromDTO()
               .ToView();

        #endregion
    }
}

UI/WebStore/Views/Catalog/Details.cshtml
@model WebStore.Domain.ViewModels.ProductViewModel
@{ ViewData["Title"] = $"Информация о товаре {Model.Name}"; }

<section>
    <div class="container">
        <vc:bread-crumbs />
        <div class="row">
            <div class="col-sm-3">
                <partial name="Partial/_LeftSideBar" />
            </div>

            <div class="col-sm-9 padding-right">
                <div class="product-details">
                    <!--product-details-->
                    <div class="col-sm-5">
                        <div class="view-product">
                            <img src="~/images/product-details/1.jpg" alt="" />
                            <h3>ZOOM</h3>
                        </div>
                        <div id="similar-product" class="carousel slide" data-ride="carousel">

                            <!-- Wrapper for slides -->
                            <div class="carousel-inner">
                                <div class="item active">
                                    <a href=""><img src="~/images/product-details/similar1.jpg" alt=""></a>
                                    <a href=""><img src="~/images/product-details/similar2.jpg" alt=""></a>
                                    <a href=""><img src="~/images/product-details/similar3.jpg" alt=""></a>
                                </div>
                                <div class="item">
                                    <a href=""><img src="~/images/product-details/similar1.jpg" alt=""></a>
                                    <a href=""><img src="~/images/product-details/similar2.jpg" alt=""></a>
                                    <a href=""><img src="~/images/product-details/similar3.jpg" alt=""></a>
                                </div>
                                <div class="item">
                                    <a href=""><img src="~/images/product-details/similar1.jpg" alt=""></a>
                                    <a href=""><img src="~/images/product-details/similar2.jpg" alt=""></a>
                                    <a href=""><img src="~/images/product-details/similar3.jpg" alt=""></a>
                                </div>

                            </div>

                            <!-- Controls -->
                            <a class="left item-control" href="#similar-product" data-slide="prev">
                                <i class="fa fa-angle-left"></i>
                            </a>
                            <a class="right item-control" href="#similar-product" data-slide="next">
                                <i class="fa fa-angle-right"></i>
                            </a>
                        </div>

                    </div>
                    <div class="col-sm-7">
                        <div class="product-information">
                            <!--/product-information-->
                            <img src="~/images/shop/@Model.ImageUrl" class="newarrival" alt="" />
                            <h2>@Model.Name</h2>
                            <p>Артикул: @Model.Id.ToString("00000000")</p>
                            <img src="~/images/product-details/rating.png" alt="" />
                            <span>
                                <span>@Model.Price.ToString("C")</span>
                                <label>Количество:</label>
                                <input type="text" value="3" />
                                <a asp-controller="Cart" asp-action="Add" asp-route-id="@Model.Id"
                                   data-id ="@Model.Id"
                                   class="btn btn-default add-to-cart cart">
                                    <i class="fa fa-shopping-cart"></i>
                                    В корзину
                                </a>
                            </span>
                            <p><b>Доступность:</b> На складе</p>
                            <p><b>Состояние:</b> Новое</p>
                            <p><b>Brand:</b> @Model?.Brand</p>
                            <a href=""><img src="~/images/product-details/share.png" class="share img-responsive" alt="" /></a>
                        </div><!--/product-information-->
                    </div>
                </div><!--/product-details-->

                <partial name="Partial/_CategoryTab" />

                <partial name="Partial/_RecomendedItems" />
            </div>
        </div>
    </div>
</section>

UI/WebStore/Views/Catalog/Index.cshtml
@model WebStore.Domain.ViewModels.CatalogViewModel
@{
    ViewData["Title"] = "Каталог товаров";
}

@*<partial name="Partial/_Advertisement"/>*@

<section>
    <div class="container">

        <vc:bread-crumbs />

        <div class="row">
            <div class="col-sm-3">
                <partial name="Partial/_LeftSideBar" />
            </div>

            <div class="col-sm-9 padding-right">
                <div id="catalog-items-container">
                    <partial name="Partial/_FeaturesItems" model="Model.Products" />
                </div>

                <paging page-model="Model.PageViewModel"
                        page-action="Index"
                        page-url-SectionId="@Model.SectionId"
                        page-url-BrandId="@Model.BrandId"
                        page-url-PageSize="@Context.Request.Query["PageSize"]">
                </paging>
            </div>
        </div>
    </div>
</section>

@section Scripts
{
    <script src="~/lib/jquery-loading-overlay/loadingoverlay.min.js"></script>
    <script src="~/js/Catalog/CatalogLogik.js" asp-append-version="true"></script>
    <script>
        $(function() {
            Catalog.init({
                getViewLink: "@Url.Action("GetFeaturesItems","Catalog")"
            });
        })
    </script>
}